export const SUBWAY_STATION_NAME_LENGTH_LIMIT = 2;
export const SUBWAY_STATION_IN_LINE_DELETE_LENGTH_LIMIT = 2;
export const SUBWAY_MAP_ITEM_NAME = 'Subway-Map';

export default {
  SUBWAY_STATION_NAME_LENGTH_LIMIT,
  SUBWAY_STATION_IN_LINE_DELETE_LENGTH_LIMIT,
  SUBWAY_MAP_ITEM_NAME
};
