const message = {
  STATION_NAME: '역 이름',
  LINE_NAME: '노선 이름',
  LINE_MANAGING: '관리',
  ADD_SECTION: '구간 등록',
  SECTION_INFORMATION: '구간을 수정할 노선을 선택해주세요.',
  OPTION: '설정',
  ORDER: '순서',
  NAME: '이름',
  ADD_STATION: '역 추가',
  ADD: '등록',
  LIST_OF_STATIONS: '지하철 역 목록',
  LIST_OF_LINES: '지하철 노선 목록',
  OPTION_DELETE: '삭제',
  START_STATION: '상행 종점',
  END_STATION: '하행 종점',
  LINE_ADD_BUTTON: '노선 추가',
  ALERT_FOR_BLANK: '공백이 아닌 이름을 입력해주세요.',
  ALERT_FOR_WRONG_NAME: '알파벳, 한글, 숫자로 이루어진 이름을 입력해주세요.',
  ALERT_FOR_OVERLAPED_NAME: '중복되지 않은 이름을 입력해주세요.',
  ALERT_FOR_LENGTH: '2글자 이상의 이름을 입력해주세요.',
  ALERT_FOR_OVERLAPED_STATION: '상행 종점역과 하행 종점역을 중복되지 않게 입력해주세요.',
  ALERT_FOR_STATION_IN_LINES: '노선에 등록된 역은 삭제할 수 없습니다.',
  ALERT_FOR_LESS_THAN_TWO: '노선에 포함된 역이 두 개 이하일 때는 역을 제거할 수 없습니다.',
  ALERT_FOR_BETWEEN_STATION_AND_STATION: '역과 역 사이에 새로운 구간을 추가해주세요.',
  ALERT_FOR_STATION_IS_IN_LINE: '노선에 중복된 역을 추가할 수 없습니다.',
  ALERT_FOR_NOT_A_NUMBER: '숫자를 입력해주세요.',
  ASK_WANT_TO_DELETE: '정말로 삭제하시겠습니까?',
  ASK_WANT_TO_DELETE_IN_LINE: '정말로 노선에서 삭제하시겠습니까?',
  STATION_INPUT_PLACEHOLDER: '역 이름을 입력해주세요.',
  LINE_INPUT_PLACEHOLDER: '노선 이름을 입력해주세요.',
  SECTION_INPUT_PLACEHOLDER: '순서',
};

export { message };
