const STATION_STORAGE_NAME = 'STATIONS';
const LINE_STORAGE_NAME = 'LINES';
const NAME_MIN_LENGTH = 2;
const SECTION_MIN_LENGTH = 2;

export { STATION_STORAGE_NAME, LINE_STORAGE_NAME, NAME_MIN_LENGTH, SECTION_MIN_LENGTH };
