export const stationText = {
  inputLabel: '역 이름',
  inputId: 'station-name-input',
  placeholder: '역 이름을 입력해주세요',
  submitId: 'station-add-button',
  submitText: '역 추가',
  inputContainer: 'input-container',
  alertDuplicateName: '중복된 역 이름이 존재합니다.',
  alertNameUnderTwo: '역 이름을 2자 이상으로 입력해 주세요.',
  resultTitle: '🚉 지하철 역 목록',
  tableHeader1: '역 이름',
  tableHeader2: '설정',
  tableId: 'station-table',
  deleteBtnClass: 'station-delete-button',
  deleteBtnText: '삭제',
  alertStationInLine: '노선에 등록된 역은 삭제할 수 없습니다.',
  alertConfirmDelete: '정말 삭제하시겠습니까?',
};

export const lineText = {
  inputLabel: '노선 이름',
  inputId: 'line-name-input',
  placeholder: '노선 이름을 입력해주세요',
  submitId: 'line-add-button',
  submitText: '노선 추가',
  startSelectorId: 'line-start-station-selector',
  startSelectorText: '상행 종점',
  endSelectorId: 'line-end-station-selector',
  endSelectorText: '하행 종점',
  alertDuplicateName: '중복된 노선 이름이 존재합니다.',
  resultTitle: '🚉 지하철 노선 목록',
  tableHeader1: '노선 이름',
  tableHeader2: '상행 종점역',
  tableHeader3: '하행 종점역',
  tableHeader4: '설정',
  tableId: 'line-table',
  deleteBtnClass: 'line-delete-button',
  deleteBtnText: '삭제',
  alertConfirmDelete: '정말 삭제하시겠습니까?',
};

export const sectionText = {
  guideText: '구간을 수정할 노선을 선택해주세요.',
  menuButtonsClass: 'section-line-menu-button',
  inputId: 'section-input',
  selectAreaId: 'section-select',
  tableId: 'section-table',
  manageText: '관리',
  registerText: '구간 등록',
  selectorId: 'section-station-selector',
  orderInputId: 'section-order-input',
  placeholder: '순서',
  submitId: 'section-add-button',
  submitText: '등록',
  tableHeader1: '순서',
  tableHeader2: '이름',
  tableHeader3: '설정',
  deleteBtnClass: 'section-delete-button',
  deleteBtnText: '노선에서 제거',
  alertStationsUnderTwo: '노선에 포함된 역이 2개 이하일 때는 역을 삭제할 수 없습니다.',
  alertConfirmDelete: '정말 삭제하시겠습니까?',
};

export const mapText = {
  resultAreaClass: 'map',
};
