const words = {
    STATIONS: "stations",
    STATION_NAME: "역 이름",
    STATION_LIST: "🚉 지하철 역 목록",
    STATION_ADD: "역 추가",
    STATION_INPUT_ALERT: "역 이름을 입력해주세요.",
    STATION_LENGTH_ALERT: "역 이름을 2글자 이상 작성해주세요.",
    STATION_DUPLICATE_ALERT: "역은 이미 등록된 역입니다.",
    STATION_NAME_INPUT: "station-name-input",
    STATION_ADD_BUTTON: "station-add-button",
    STATION_DELETE_BUTTON: "station-delete-button",
    STATION_TABLE_TBODY: "station-table-tbody",

    LINES: "lines",
    LINE_NAME: "노선 이름",
    LINE_LIST: "🚉 지하철 노선 목록",
    LINE_START_STATION: "상행 종점",
    LINE_END_STATION: "하행 종점",
    LINE_ADD: "노선 추가",
    LINE_INPUT_ALERT: "노선 이름을 입력해주세요.",
    LINE_DUPLICATE_ALERT: "은 이미 등록된 노선입니다.",
    LINE_SAME_STATION_ALERT:"상행종점역과 하행종점역을 다르게 선택해주세요.",
    LINE_NAME_INPUT: "line-name-input",
    LINE_STATION_TEXT: "line-station-text",
    LINE_START_STATION_SELECTOR: "line-start-station-selector",
    LINE_END_STATION_SELECTOR: "line-end-station-selector",
    LINE_ADD_BUTTON: "line_add_button",
    LINE_DELETE_BUTTON: "line-delete-button",
    LINE_TABLE_TBODY: "line-table-tbody",

    SECTION_LINE_SELECT_TEXT: "구간을 수정할 노선을 선택해주세요.",
    SECTION_DELETE_TEXT: "노선에서 제거",
    SECTION_ADD_TEXT: "구간 등록",
    SECTION_LINE_MENU_BUTTON: "section-line-menu-button",
    SECTION_MANAGEMENT_PART: "section-management-part",
    SECTION_STATION_SELECTOR: "section-station-selector",
    SECTION_ORDER_INPUT: "section-order-input",
    SECTION_ADD_BUTTON: "section-add-button",
    SECTION_ADD_TEXT_ID: "section-add-text",
    SECTION_DELETE_BUTTON: "section-delete-button",
    SECTION_TABLE_TBODY: "section-table-tbody",

    DELETE: "삭제",
    DELETE_ALERT: "정말로 삭제하시겠습니까?",
    SETTING: "설정",
    MANAGEMENT: "관리",
    ENROLLMENT: "등록",
    NAME: "이름",
    ORDER: "순서"
}

export default words;