const words = {
    STATIONS: "stations",
    STATION_NAME: "역 이름",
    STATION_LIST: "🚉 지하철 역 목록",
    STATION_ADD: "역 추가",
    STATION_INPUT_ALERT: "역 이름을 입력해주세요.",
    STATION_LENGTH_ALERT: "역 이름을 2글자 이상 작성해주세요.",
    STATION_DUPLICATE_ALERT: "역은 이미 등록된 역입니다.",
    STATION_NAME_INPUT: "station-name-input",
    STATION_ADD_BUTTON: "station-add-button",
    STATION_DELETE_BUTTON: "station-delete-button",
    STATION_TABLE_TBODY: "station-table-tbody",

    LINES: "lines",
    LINE_NAME: "노선 이름",
    LINE_LIST: "🚉 지하철 노선 목록",
    LINE_START_STATION: "상행 종점",
    LINE_END_STATION: "하행 종점",
    LINE_ADD: "노선 추가",
    LINE_INPUT_ALERT: "노선 이름을 입력해주세요.",
    LINE_DUPLICATE_ALERT: "은 이미 등록된 노선입니다.",
    LINE_NAME_INPUT: "line-name-input",
    LINE_STATION_TEXT: "line-station-text",
    LINE_START_STATION_SELECTOR: "line-start-station-selector",
    LINE_END_STATION_SELECTOR: "line-end-station-selector",
    LINE_ADD_BUTTON: "line_add_button",
    LINE_DELETE_BUTTON: "line-delete-button",
    LINE_TABLE_TBODY: "line-table-tbody",

    DELETE: "삭제",
    DELETE_ALERT: "정말로 삭제하시겠습니까?",
    SETTING: "설정",
}

export default words;